import type { INodeProperties } from 'n8n-workflow';
import { show, address, csvToArray } from './shared';

export const agentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['agent'] } },
		options: [
			{
				name: 'Get Cards',
				value: 'getCards',
				action: 'Get agent cards',
				description: 'Every agent with an owner address and at least one published skill, from both populations. Filter by skill, chain or protocol.',
				routing: { request: { method: 'GET', url: '/agents/cards' } },
			},
			{
				name: 'Get Market',
				value: 'getMarket',
				action: 'Get market statistics',
				description: 'Aggregate volume, completion rate and price band. This returns statistics, not a list of agents — use Match to find candidates.',
				routing: { request: { method: 'GET', url: '/agents/market' } },
			},
			{
				name: 'Get Providers',
				value: 'getProviders',
				action: 'Get providers',
				description: 'The agents doing work, with jobs done and USDC earned',
				routing: { request: { method: 'GET', url: '/agents/providers' } },
			},
			{
				name: 'Get Registered',
				value: 'getRegistered',
				action: 'Get registered agents',
				description: 'Agents that joined the index by registering a card URL',
				routing: { request: { method: 'GET', url: '/agents/registered' } },
			},
			{
				name: 'Get Reputation',
				value: 'getReputation',
				action: 'Get the reputation of an address',
				description: 'What an address has sold, bought and judged. Counts from the public job log, not a score.',
				routing: { request: { method: 'GET', url: '=/agents/who/{{$parameter.address}}' } },
			},
			{
				name: 'Get Wire-Ready',
				value: 'getWireReady',
				action: 'List agents that answered on the wire',
				description: 'Agents that answered when the layer called them in their own protocol (or answered with a priced x402 wall), best trust first. A rank is card presence; the wire is who is home. Stage: listing.',
				routing: { request: { method: 'GET', url: '/registry/agents', qs: { wire: 'ready' } } },
			},
			{
				name: 'Match',
				value: 'match',
				action: 'Match agents to skills',
				description: 'Rank candidates across both populations. Every required skill must be covered to be eligible; partial matches come back marked with what they lack.',
				routing: { request: { method: 'POST', url: '/match' } },
			},
			{
				name: 'Plan Enrollment',
				value: 'planEnrollment',
				action: 'Plan enrolling a capability as an agent',
				description: 'What it takes to make a workflow hireable: the card to publish, the steps, and the deposit you must hold. Registers nothing.',
				routing: { request: { method: 'POST', url: '/enroll/plan' } },
			},
			{
				name: 'Publish As Seller',
				value: 'publishAsSeller',
				action: 'Publish this workflow as a hireable ERC-8183 seller',
				description: 'Turn this workflow’s webhook into a seller of record: price bounds, concurrency, skills. Returns the prepared, UNSIGNED enrollment call for your own signer — the node holds no key. Once you sign and send, buyers find you in the directory and route jobs to the webhook.',
				routing: { request: { method: 'POST', url: '/enroll/plan' } },
			},
			{
				name: 'Register',
				value: 'register',
				action: 'Register an agent card',
				description: 'Join the index by giving the URL where the agent publishes its own card. The card is fetched server-side.',
				routing: { request: { method: 'POST', url: '/agents/register' } },
			},
		],
		default: 'match',
	},
	address('Address', 'address', 'agent', ['getReputation'], 'The counterparty to look up.'),
	{
		displayName: 'Required Skills',
		name: 'required_skills',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'chain-analytics, summarization',
		description: 'Comma-separated, lowercase kebab-case tags. All of them must be covered for a candidate to be eligible.',
		displayOptions: show('agent', ['match']),
		routing: { send: { type: 'body', property: 'required_skills', value: csvToArray } },
	},
	{
		displayName: 'Options',
		name: 'matchOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('agent', ['match']),
		options: [
			{
				displayName: 'Budget (USDC)',
				name: 'budget_usdc',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'budget_usdc' } },
			},
			{
				displayName: 'Kind',
				name: 'kind',
				type: 'options',
				default: 'n8n',
				options: [
					{ name: 'Workflow Agent', value: 'n8n' },
					{ name: 'On-Chain Agent', value: 'onchain' },
				],
				routing: { send: { type: 'body', property: 'kind' } },
			},
			{
				displayName: 'Verify Mode',
				name: 'verify',
				type: 'string',
				default: 'self',
				routing: { send: { type: 'body', property: 'verify' } },
			},
		],
	},
	{
		...address('Operator', 'operator', 'agent', ['planEnrollment', 'publishAsSeller'], 'The address that earns the price and locks the deposit.'),
		routing: { send: { type: 'body', property: 'operator' } },
	},
	{
		displayName: 'Webhook URL',
		name: 'endpoint',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://you.app.n8n.cloud/webhook/taifoon-hire',
		description: 'The public https webhook of the running workflow that will take the jobs',
		displayOptions: show('agent', ['planEnrollment', 'publishAsSeller']),
		routing: { send: { type: 'body', property: 'endpoint' } },
	},
	{
		displayName: 'Minimum Price (USDC)',
		name: 'priceMin',
		type: 'number',
		typeOptions: { numberPrecision: 6, minValue: 0 },
		default: 0.01,
		required: true,
		displayOptions: show('agent', ['planEnrollment', 'publishAsSeller']),
		routing: { send: { type: 'body', property: 'price_usdc.min' } },
	},
	{
		displayName: 'Maximum Price (USDC)',
		name: 'priceMax',
		type: 'number',
		typeOptions: { numberPrecision: 6, minValue: 0 },
		default: 0.05,
		required: true,
		description: 'The deposit you must hold per job is sized against this',
		displayOptions: show('agent', ['planEnrollment', 'publishAsSeller']),
		routing: { send: { type: 'body', property: 'price_usdc.max' } },
	},
	{
		displayName: 'Options',
		name: 'enrollOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('agent', ['planEnrollment', 'publishAsSeller']),
		options: [
			{
				displayName: 'Community Node Name',
				name: 'nodeName',
				type: 'string',
				default: '',
				placeholder: 'n8n-nodes-typesafe',
				description: 'Derive the card from this indexed community node',
				routing: { send: { type: 'body', property: 'capability', value: '={{ $value ? { kind: "node", name: $value } : undefined }}' } },
			},
			{
				displayName: 'Concurrent Jobs',
				name: 'concurrent_jobs',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 1,
				description: 'How many jobs you expect in flight at once. Working capital is the deposit times this.',
				routing: { send: { type: 'body', property: 'concurrent_jobs' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Skills',
				name: 'skills',
				type: 'string',
				default: '',
				placeholder: 'typed-decisions, triage',
				description: 'Comma-separated. Overrides the skills derived from the capability.',
				routing: { send: { type: 'body', property: 'skills', value: csvToArray } },
			},
			{
				displayName: 'Template ID',
				name: 'templateId',
				type: 'number',
				default: 0,
				description: 'Derive the card from this n8n workflow template (the number in its n8n.io URL)',
				routing: { send: { type: 'body', property: 'capability', value: '={{ $value ? { kind: "template", id: $value } : undefined }}' } },
			},
		],
	},
	{
		displayName: 'Card URL',
		name: 'card_url',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/agent-card.json',
		description:
			'An https URL serving the card as JSON: <code>address</code>, <code>kind</code> (n8n or onchain), <code>skills</code>, and for an n8n agent its webhook as <code>endpoint</code>. Register the same URL again to refresh it.',
		displayOptions: show('agent', ['register']),
		routing: { send: { type: 'body', property: 'card_url' } },
	},
	{
		displayName: 'Filters',
		name: 'cardFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: show('agent', ['getCards']),
		options: [
			{
				displayName: 'Chain ID',
				name: 'chain',
				type: 'number',
				default: 8453,
				description: 'Only agents registered on this chain: 8453 Base, 1 Ethereum, 5042 Arc, 4663 Robinhood',
				routing: { send: { type: 'query', property: 'chain' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'query', property: 'limit' } },
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 0,
				description: 'Skip this many matching agents, to page through the index',
				routing: { send: { type: 'query', property: 'offset' } },
			},
			{
				displayName: 'Skill',
				name: 'skill',
				type: 'string',
				default: '',
				placeholder: 'sentiment-analysis',
				description: 'Only agents publishing this exact skill tag. The response lists the tags in use under skills_seen.',
				routing: { send: { type: 'query', property: 'skill' } },
			},
			{
				displayName: 'Speaks',
				name: 'speaks',
				type: 'options',
				default: 'a2a',
				description: 'Only agents whose endpoint speaks this protocol',
				options: [
					{ name: 'A2A', value: 'a2a' },
					{ name: 'Declared (Unspecified)', value: 'declared' },
					{ name: 'MCP', value: 'mcp' },
					{ name: 'Service', value: 'service' },
					{ name: 'Web', value: 'web' },
				],
				routing: { send: { type: 'query', property: 'speaks' } },
			},
		],
	},
	{
		displayName: 'Chain',
		name: 'wireChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }, { name: 'Arc (5042)', value: 5042 }, { name: 'BSC (56)', value: 56 }, { name: 'Celo (42220)', value: 42220 }, { name: 'Ethereum (1)', value: 1 }, { name: 'Abstract (2741)', value: 2741 }, { name: 'Arbitrum (42161)', value: 42161 }],
		default: 8453,
		required: true,
		displayOptions: show('agent', ['getWireReady']),
		routing: { send: { type: 'query', property: 'chain' } },
	},
	{
		displayName: 'Limit',
		name: 'wireLimit',
		type: 'number',
		default: 20,
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: show('agent', ['getWireReady']),
		routing: { send: { type: 'query', property: 'limit' } },
	},
];
