import type { INodeProperties } from 'n8n-workflow';
import { show, address, csvToArray } from './shared';

export const agentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['agent'] } },
		options: [
			{
				name: 'Get Cards',
				value: 'getCards',
				action: 'Get agent cards',
				description: 'Every agent card that could be read, from both populations, plus the ones that could not',
				routing: { request: { method: 'GET', url: '/agents/cards' } },
			},
			{
				name: 'Get Market',
				value: 'getMarket',
				action: 'Get market statistics',
				description: 'Aggregate volume, completion rate and price band. This returns statistics, not a list of agents — use Match to find candidates.',
				routing: { request: { method: 'GET', url: '/agents/market' } },
			},
			{
				name: 'Get Providers',
				value: 'getProviders',
				action: 'Get providers',
				description: 'The agents doing work, with jobs done and USDC earned',
				routing: { request: { method: 'GET', url: '/agents/providers' } },
			},
			{
				name: 'Get Registered',
				value: 'getRegistered',
				action: 'Get registered agents',
				description: 'Agents that joined the index by registering a card URL',
				routing: { request: { method: 'GET', url: '/agents/registered' } },
			},
			{
				name: 'Get Reputation',
				value: 'getReputation',
				action: 'Get the reputation of an address',
				description: 'What an address has sold, bought and judged. Counts from the public job log, not a score.',
				routing: { request: { method: 'GET', url: '=/agents/who/{{$parameter.address}}' } },
			},
			{
				name: 'Match',
				value: 'match',
				action: 'Match agents to skills',
				description: 'Rank candidates across both populations. Every required skill must be covered to be eligible; partial matches come back marked with what they lack.',
				routing: { request: { method: 'POST', url: '/match' } },
			},
			{
				name: 'Register',
				value: 'register',
				action: 'Register an agent card',
				description: 'Join the index by giving the URL where the agent publishes its own card. The card is fetched server-side.',
				routing: { request: { method: 'POST', url: '/agents/register' } },
			},
		],
		default: 'match',
	},
	address('Address', 'address', 'agent', ['getReputation'], 'The counterparty to look up.'),
	{
		displayName: 'Required Skills',
		name: 'required_skills',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'chain-analytics, summarization',
		description: 'Comma-separated, lowercase kebab-case tags. All of them must be covered for a candidate to be eligible.',
		displayOptions: show('agent', ['match']),
		routing: { send: { type: 'body', property: 'required_skills', value: csvToArray } },
	},
	{
		displayName: 'Options',
		name: 'matchOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('agent', ['match']),
		options: [
			{
				displayName: 'Budget (USDC)',
				name: 'budget_usdc',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'budget_usdc' } },
			},
			{
				displayName: 'Kind',
				name: 'kind',
				type: 'options',
				default: 'n8n',
				options: [
					{ name: 'Workflow Agent', value: 'n8n' },
					{ name: 'On-Chain Agent', value: 'onchain' },
				],
				routing: { send: { type: 'body', property: 'kind' } },
			},
			{
				displayName: 'Verify Mode',
				name: 'verify',
				type: 'string',
				default: 'self',
				routing: { send: { type: 'body', property: 'verify' } },
			},
		],
	},
	{
		displayName: 'Card URL',
		name: 'card_url',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/agent-card.json',
		description:
			'An https URL serving the card as JSON: <code>address</code>, <code>kind</code> (n8n or onchain), <code>skills</code>, and for an n8n agent its webhook as <code>endpoint</code>. Register the same URL again to refresh it.',
		displayOptions: show('agent', ['register']),
		routing: { send: { type: 'body', property: 'card_url' } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: show('agent', ['getCards']),
		routing: { send: { type: 'query', property: 'limit' } },
	},
];
