import type { INodeProperties } from 'n8n-workflow';
import { ASSURANCE_CHAINS, show, address } from './shared';

export const assuranceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['assurance'] } },
		options: [
			{
				name: 'Build Call',
				value: 'buildCall',
				action: 'Build an unsigned call',
				description: 'The exact calldata for an insured job, with its effect in plain words and who must sign. Nothing is signed or sent.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
			{
				name: 'Get Deployment',
				value: 'getDeployment',
				action: 'Get the assurance deployment',
				description: 'Where the hook and pool factory are deployed, who may upgrade them, and the rules the contracts enforce',
				routing: { request: { method: 'GET', url: '/assurance' } },
			},
			{
				name: 'Get Pools',
				value: 'getPools',
				action: 'Get coverage pools',
				description: 'Per seller: its settled record, premium interval, and its coverage pool read from chain. Never aggregated across sellers.',
				routing: { request: { method: 'GET', url: '/pools' } },
			},
			{
				name: 'Get Quote',
				value: 'getQuote',
				action: 'Get a quote for the guarantee',
				description: 'Price the premium from that seller\'s own settled record, and learn now whether these terms could settle',
				routing: { request: { method: 'POST', url: '/assurance/quote' } },
			},
			{
				name: 'Stamp Grade',
				value: 'stampGrade',
				action: 'Stamp a grade on chain',
				description: 'The unsigned call that appends a grade digest to the GradeStampRegistry (immutable, append-only; on the Taifoon devnet today). Any subject, any stamper. Nothing is signed or sent.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
		],
		default: 'getQuote',
	},
	{
		displayName: 'Chain',
		name: 'chainId',
		type: 'options',
		options: ASSURANCE_CHAINS,
		default: 8453,
		required: true,
		displayOptions: show('assurance', ['getQuote', 'buildCall', 'stampGrade']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		...address('Seller', 'seller', 'assurance', ['getQuote'], 'The agent whose record prices the premium.'),
		routing: { send: { type: 'body', property: 'seller' } },
	},
	{
		displayName: 'Price (Smallest Unit)',
		name: 'price',
		type: 'string',
		default: '',
		required: true,
		placeholder: '100000000',
		description: 'An integer in the token\'s smallest unit. 100 USDC is <code>100000000</code>.',
		displayOptions: show('assurance', ['getQuote']),
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Deposit (Smallest Unit)',
		name: 'deposit',
		type: 'string',
		default: '',
		description: 'What the seller will lock. It must exceed the price, or the quote refuses and says why.',
		displayOptions: show('assurance', ['getQuote']),
		routing: { send: { type: 'body', property: 'deposit', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Kind',
		name: 'stampKind',
		type: 'hidden',
		default: 'stamp',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.kind' } },
	},
	{
		displayName: 'Subject (Bytes32)',
		name: 'stampSubject',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'SubjectOf(chainId, contract, jobId) — the judge/grade rows carry it as <code>subject</code>',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.subject' } },
	},
	{
		displayName: 'Grade Digest (Bytes32)',
		name: 'stampDigest',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'Sha256 over the canonical grade — the judge/grade rows carry it as <code>digest</code>; anyone recomputes it from the grade',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.digest' } },
	},
	{
		displayName: 'Verdict',
		name: 'stampVerdict',
		type: 'options',
		options: [
			{ name: 'Delivered as Specified', value: 1 },
			{ name: 'Delivered with Defects', value: 2 },
			{ name: 'Not Delivered', value: 3 },
			{ name: 'Cannot Determine', value: 4 },
		],
		default: 4,
		description: 'The closed vocabulary; none of it means dishonesty',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.verdict' } },
	},
	{
		displayName: 'Mode',
		name: 'stampMode',
		type: 'options',
		options: [
			{ name: 'Calibrated (Jev)', value: 2 },
			{ name: 'Deterministic', value: 1 },
		],
		default: 2,
		description: 'A calibrated grade is an attestation from a System One model, never a proof; a deterministic one is a digest anyone recomputes',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.mode' } },
	},
	{
		displayName: 'Model',
		name: 'stampModel',
		type: 'string',
		default: 'jev-1.13.0',
		description: 'Model version pinned in the stamp (up to 64 bytes)',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.model' } },
	},
	{
		displayName: 'URI',
		name: 'stampUri',
		type: 'string',
		default: '',
		placeholder: 'https://www.taifoon.io/v1/judge/trace/8453/81067',
		description: 'Where the long form of the grade can be read (up to 512 bytes)',
		displayOptions: show('assurance', ['stampGrade']),
		routing: { send: { type: 'body', property: 'action.uri' } },
	},
	{
		displayName: 'Action',
		name: 'action',
		type: 'json',
		default: '{\n  "kind": "complete",\n  "jobId": "0x"\n}',
		required: true,
		description:
			'One of: <code>fund-job</code>, <code>submit</code>, <code>complete</code>, <code>expire</code>, <code>reject</code>, <code>create-pool</code>, <code>back-seller</code>. Send an empty object to get the list with an example.',
		displayOptions: show('assurance', ['buildCall']),
		routing: { send: { type: 'body', property: 'action', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: show('assurance', ['getPools']),
		routing: { send: { type: 'query', property: 'limit' } },
	},
];
