import type { INodeProperties } from 'n8n-workflow';
import { show } from './shared';

/**
 * Catalog: every hireable agent resold through the layer, with the seller's price, ours (+49 bps) and the cover; and the
 * listings (a seller that claimed its endpoint and was verified by a probe: candidate → claimed → listed).
 */
export const catalogOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['catalog'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				action: 'Get a catalog entry',
				description: 'One entry: seller, price, cover, grade and how to buy it',
				routing: { request: { method: 'GET', url: '=/catalog/{{$parameter.catalogId}}' } },
			},
			{
				name: 'Get Listing',
				value: 'getListing',
				action: 'Get a listing',
				description: 'One listing: its state and why, stage, endpoint, card, classes, price, payout and whose',
				routing: { request: { method: 'GET', url: '=/listings/{{$parameter.listingId}}' } },
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many catalog entries',
				description: 'Search the resale catalog. A buy_now entry is bought with Demand → Post → A Catalog Entry.',
				routing: { request: { method: 'GET', url: '/catalog' } },
			},
			{
				name: 'Get Many Listings',
				value: 'getManyListings',
				action: 'Get many listings',
				description: 'The listings with their counts and the funnel (candidate → claimed → listed)',
				routing: { request: { method: 'GET', url: '/listings' } },
			},
		],
		default: 'getAll',
	},
	{
		displayName: 'Catalog ID',
		name: 'catalogId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'cat_…',
		displayOptions: show('catalog', ['get']),
	},
	{
		displayName: 'Filters',
		name: 'catalogFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: show('catalog', ['getAll']),
		options: [
			{
				displayName: 'Class',
				name: 'class',
				type: 'string',
				default: '',
				routing: { send: { type: 'query', property: 'class', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'query', property: 'limit' } },
			},
			{
				displayName: 'Protocol',
				name: 'protocol',
				type: 'string',
				default: '',
				placeholder: 'mcp, a2a, n8n, x402',
				routing: { send: { type: 'query', property: 'protocol', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Search',
				name: 'q',
				type: 'string',
				default: '',
				routing: { send: { type: 'query', property: 'q', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Buy Now', value: 'buy_now' },
					{ name: 'Covered', value: 'covered' },
					{ name: 'Openable', value: 'openable' },
					{ name: 'Priced', value: 'priced' },
					{ name: 'Quote on Request', value: 'quote_on_request' },
					{ name: 'Ready', value: 'ready' },
					{ name: 'Served', value: 'served' },
				],
				default: 'buy_now',
				routing: { send: { type: 'query', property: 'status' } },
			},
		],
	},
	{
		displayName: 'Listing ID',
		name: 'listingId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'ls_…',
		displayOptions: show('catalog', ['getListing']),
	},
	{
		displayName: 'Filters',
		name: 'listingFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: show('catalog', ['getManyListings']),
		options: [
			{
				displayName: 'Class',
				name: 'class',
				type: 'string',
				default: '',
				placeholder: 'mcp.digest',
				routing: { send: { type: 'query', property: 'class', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Kind',
				name: 'kind',
				type: 'options',
				options: [
					{ name: 'A2A', value: 'a2a' },
					{ name: 'MCP', value: 'mcp' },
					{ name: 'N8n', value: 'n8n' },
					{ name: 'X402', value: 'x402' },
				],
				default: 'n8n',
				routing: { send: { type: 'query', property: 'kind' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'query', property: 'limit' } },
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'options',
				options: [
					{ name: 'Candidate', value: 'candidate' },
					{ name: 'Claimed', value: 'claimed' },
					{ name: 'Delisted', value: 'delisted' },
					{ name: 'Listed', value: 'listed' },
					{ name: 'Paused', value: 'paused' },
				],
				default: 'listed',
				routing: { send: { type: 'query', property: 'state' } },
			},
			{
				displayName: 'Whose',
				name: 'whose',
				type: 'options',
				options: [
					{ name: 'Ours', value: 'ours' },
					{ name: 'Outside', value: 'outside' },
				],
				default: 'outside',
				routing: { send: { type: 'query', property: 'whose' } },
			},
		],
	},
];
