import type { INodeProperties } from 'n8n-workflow';
import { show } from './shared';

/**
 * Demand: say what you need, not whom to hire. The layer's auto-match loop claims the demand, picks the
 * seller (SELLER_CHOICE_v3), hires it, grades the reply by code and settles on the devnet 36927.
 * Poll Get until `state` is settled, unmatched, failed or cancelled. Nothing here signs anything.
 */
export const demandOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['demand'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				action: 'Get a demand',
				description:
					'One demand and its path: open → claimed → matched → hired → graded → settling → settled, or unmatched / failed with why. Poll this until the state ends.',
				routing: { request: { method: 'GET', url: '=/demands/{{$parameter.demandId}}' } },
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many demands',
				description: 'Demands, newest first, each with every step the auto-match loop wrote on it',
				routing: { request: { method: 'GET', url: '/demands' } },
			},
			{
				name: 'Post',
				value: 'post',
				action: 'Post a demand',
				description:
					'Post what you need: in words, as a job of a class, or a catalog entry to buy. Answers 201 with the demand (state open). A 4xx names the classes or what is missing, and its next_step.',
				routing: { request: { method: 'POST', url: '/demands' } },
			},
		],
		default: 'post',
	},
	{
		displayName: 'Demand ID',
		name: 'demandId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'dm_…',
		description: 'The ID that Post answered',
		displayOptions: show('demand', ['get']),
	},
	{
		displayName: 'Ask For',
		name: 'demandMode',
		type: 'options',
		options: [
			{ name: 'A Catalog Entry', value: 'catalog', description: 'Buy a buy_now entry of GET /v1/catalog by its ID' },
			{ name: 'A Job of a Class', value: 'class', description: 'Name the class and send its input (GET /v1/classes)' },
			{ name: 'The Work in Words', value: 'need', description: 'The layer maps the words to a class by fixed rules, never a model' },
		],
		default: 'need',
		displayOptions: show('demand', ['post']),
	},
	{
		displayName: 'Need',
		name: 'need',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		required: true,
		placeholder: 'e.g. the sha256 digest of the text "hello"',
		description: 'The work, in words. Quote exact inputs (the text, the numbers) inside the sentence.',
		routing: { send: { type: 'body', property: 'need' } },
		displayOptions: { show: { resource: ['demand'], operation: ['post'], demandMode: ['need'] } },
	},
	{
		displayName: 'Catalog ID',
		name: 'demandCatalogId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'cat_…',
		description: 'A buy_now entry of GET /v1/catalog. The loop hires that seller first.',
		routing: { send: { type: 'body', property: 'catalog_id' } },
		displayOptions: { show: { resource: ['demand'], operation: ['post'], demandMode: ['catalog'] } },
	},
	{
		displayName: 'Work in Words',
		name: 'catalogNeed',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		placeholder: 'e.g. compile these into typed questions. Rules: …',
		description: 'The job for that seller, in words (the catalog entry’s buy.body shows an example). Left empty, the entry’s class runs on its default input.',
		routing: { send: { type: 'body', property: 'need', value: '={{ $value || undefined }}' } },
		displayOptions: { show: { resource: ['demand'], operation: ['post'], demandMode: ['catalog'] } },
	},
	{
		displayName: 'Class',
		name: 'demandClass',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. mcp.digest',
		description: 'A class the auto-match loop runs (GET /v1/classes)',
		routing: { send: { type: 'body', property: 'class' } },
		displayOptions: { show: { resource: ['demand'], operation: ['post'], demandMode: ['class'] } },
	},
	{
		displayName: 'Input (JSON)',
		name: 'demandInput',
		type: 'json',
		default: '{}',
		required: true,
		description: 'The class input, as GET /v1/classes describes it',
		routing: { send: { type: 'body', property: 'input', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
		displayOptions: { show: { resource: ['demand'], operation: ['post'], demandMode: ['class'] } },
	},
	{
		displayName: 'Options',
		name: 'demandOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('demand', ['post']),
		options: [
			{
				displayName: 'Buyer Label',
				name: 'buyerLabel',
				type: 'string',
				default: '',
				description: 'Your own label for this demand; the explorer shows it',
				routing: { send: { type: 'body', property: 'buyer_label', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Class (for Words or Catalog)',
				name: 'classHint',
				type: 'string',
				default: '',
				description: 'Settle the class when the words could mean two, or pick which class of a catalog entry',
				routing: { send: { type: 'body', property: 'class', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Dry Run',
				name: 'dryRun',
				type: 'boolean',
				default: false,
				description: 'Whether to answer the mapping and the cover preview only, keeping nothing',
				routing: { send: { type: 'body', property: 'dry_run', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Price (Units)',
				name: 'priceUnits',
				type: 'number',
				default: 50000,
				description: 'The job price in dUSDC units (6 decimals) on the devnet 36927',
				routing: { send: { type: 'body', property: 'price_units' } },
			},
		],
	},
	{
		displayName: 'State',
		name: 'demandState',
		type: 'options',
		options: [
			{ name: 'Any', value: '' },
			{ name: 'Cancelled', value: 'cancelled' },
			{ name: 'Claimed', value: 'claimed' },
			{ name: 'Failed', value: 'failed' },
			{ name: 'Graded', value: 'graded' },
			{ name: 'Hired', value: 'hired' },
			{ name: 'Matched', value: 'matched' },
			{ name: 'Open', value: 'open' },
			{ name: 'Settled', value: 'settled' },
			{ name: 'Settling', value: 'settling' },
			{ name: 'Unmatched', value: 'unmatched' },
		],
		default: '',
		routing: { send: { type: 'query', property: 'state', value: '={{ $value || undefined }}' } },
		displayOptions: show('demand', ['getAll']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { send: { type: 'query', property: 'limit' } },
		displayOptions: show('demand', ['getAll']),
	},
];
