import type { INodeProperties } from 'n8n-workflow';
import { show, address, csvToArray } from './shared';

export const handshakeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['handshake'] } },
		options: [
			{
				name: 'Attach Job',
				value: 'attachJob',
				action: 'Attach a job to a handshake',
				description: 'Once the job exists on chain, attach it. From then on the handshake\'s state is read from the chain.',
				routing: { request: { method: 'POST', url: '=/handshake/{{$parameter.handshakeId}}' } },
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a handshake',
				description: 'Recorded events, plus what the chain says about the job right now, and which of the two the state came from',
				routing: { request: { method: 'GET', url: '=/handshake/{{$parameter.handshakeId}}' } },
			},
			{
				name: 'Open',
				value: 'open',
				action: 'Open a handshake',
				description: 'Record an offer to a chosen candidate and get the exact next call. The broker routes and records; it never signs.',
				routing: { request: { method: 'POST', url: '/handshake' } },
			},
		],
		default: 'open',
	},
	{
		displayName: 'Handshake ID',
		name: 'handshakeId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'hs_…',
		displayOptions: show('handshake', ['get', 'attachJob']),
	},
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '80926 or 0x…',
		displayOptions: show('handshake', ['attachJob']),
		routing: { send: { type: 'body', property: 'jobId' } },
	},
	{
		...address('Candidate Address', 'candidateAddress', 'handshake', ['open'], 'The agent being offered the job.'),
		routing: { send: { type: 'body', property: 'candidate.address' } },
	},
	{
		displayName: 'Candidate Kind',
		name: 'candidateKind',
		type: 'options',
		default: 'n8n',
		required: true,
		options: [
			{ name: 'Workflow Agent', value: 'n8n' },
			{ name: 'On-Chain Agent', value: 'onchain' },
			{ name: 'MCP Server', value: 'mcp' },
			{ name: 'A2A Agent', value: 'a2a' },
		],
		displayOptions: show('handshake', ['open']),
		routing: { send: { type: 'body', property: 'candidate.kind' } },
	},
	{
		displayName: 'Task',
		name: 'task',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		required: true,
		description: 'The work, in words',
		displayOptions: show('handshake', ['open']),
		routing: { send: { type: 'body', property: 'task' } },
	},
	{
		displayName: 'Options',
		name: 'openOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('handshake', ['open']),
		options: [
			{
				displayName: 'Arguments (JSON)',
				name: 'args',
				type: 'json',
				default: '{}',
				description: 'The arguments of the MCP tool call, when the offer is dispatched to an MCP server',
				routing: { send: { type: 'body', property: 'args', value: '={{ typeof $value === "string" ? JSON.parse($value || "{}") : $value }}' } },
			},
			{
				displayName: 'Budget (USDC)',
				name: 'budget_usdc',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'budget_usdc' } },
			},
			{
				displayName: 'Chain ID',
				name: 'chain',
				type: 'string',
				default: '8453',
				routing: { send: { type: 'body', property: 'chain' } },
			},
			{
				displayName: 'Dispatch Offer',
				name: 'dispatch',
				type: 'boolean',
				default: false,
				description:
					'Whether the broker should deliver the offer to the provider in its own protocol (an n8n webhook, an MCP tool call, an A2A message). It only ever speaks to an endpoint the agent published in its own card; otherwise the offer is returned for you to deliver. The delivery comes back with its reply head, digest and latency.',
				routing: { send: { type: 'body', property: 'dispatch' } },
			},
			{
				displayName: 'Endpoint',
				name: 'endpoint',
				type: 'string',
				default: '',
				placeholder: 'https://…/mcp',
				description: 'The candidate’s published endpoint (an MCP or A2A URL). The broker only ever speaks to an endpoint the agent’s own card lists.',
				routing: { send: { type: 'body', property: 'candidate.endpoint', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Hirer',
				name: 'hirer',
				type: 'string',
				default: '',
				placeholder: '0x…',
				routing: { send: { type: 'body', property: 'hirer' } },
			},
			{
				displayName: 'Required Skills',
				name: 'required_skills',
				type: 'string',
				default: '',
				placeholder: 'chain-analytics, summarization',
				routing: { send: { type: 'body', property: 'required_skills', value: csvToArray } },
			},
			{
				displayName: 'Tool',
				name: 'tool',
				type: 'string',
				default: '',
				placeholder: 'taifoon_proof',
				description: 'The MCP tool to call when the offer is dispatched to an MCP server; leave empty to be offered the tools to choose from',
				routing: { send: { type: 'body', property: 'tool', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Verify Mode',
				name: 'verify',
				type: 'string',
				default: 'self',
				routing: { send: { type: 'body', property: 'verify' } },
			},
		],
	},
];
