import type { INodeProperties } from 'n8n-workflow';
import { CHAINS, ASSURANCE_CHAINS, show, address } from './shared';

export const jobOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['job'] } },
		options: [
			{
				name: 'Create Offer',
				value: 'createOffer',
				action: 'Create a job offer',
				description: 'Price a job and get the unsigned calls that fund it. Nothing is signed or sent.',
				routing: { request: { method: 'POST', url: '/jobs' } },
			},
			{
				name: 'Get Changed',
				value: 'getChanged',
				action: 'Get jobs that changed',
				description: 'Jobs that changed at or after a cursor, oldest first, with the cursor for the next call',
				routing: { request: { method: 'GET', url: '/jobs' } },
			},
			{
				name: 'Get Ledger',
				value: 'getLedger',
				action: 'Get the job ledger',
				description: 'Raw ledger rows, filterable by state and by who took part',
				routing: { request: { method: 'GET', url: '/agents/ledger' } },
			},
		],
		default: 'getChanged',
	},

	// ── Get Changed ──
	{
		displayName: 'Since (Cursor)',
		name: 'since',
		type: 'string',
		default: '0',
		required: true,
		description:
			'Pass back the <code>cursor</code> from the previous response, unchanged. It looks like <code>1789878191.80901</code>: a timestamp plus a job ID, so that jobs sharing a second page correctly. A plain Unix timestamp also works for a first call.',
		displayOptions: show('job', ['getChanged']),
		routing: { send: { type: 'query', property: 'since' } },
	},
	{
		displayName: 'Filters',
		name: 'changedFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: show('job', ['getChanged']),
		options: [
			{
				displayName: 'Buyer',
				name: 'buyer',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'Only jobs this address is buying',
				routing: { send: { type: 'query', property: 'buyer' } },
			},
			{
				displayName: 'Chain',
				name: 'chain',
				type: 'options',
				options: CHAINS,
				default: 8453,
				routing: { send: { type: 'query', property: 'chain' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'query', property: 'limit' } },
			},
			{
				displayName: 'Participant',
				name: 'participant',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'Only jobs this address is buying or selling',
				routing: { send: { type: 'query', property: 'participant' } },
			},
			{
				displayName: 'Seller',
				name: 'seller',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'Only jobs this address is selling',
				routing: { send: { type: 'query', property: 'seller' } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'done',
				description: 'A job ends in exactly one of four ways. Open is still in flight and is not an ending.',
				options: [
					{ name: 'Cheat (Adjudicated)', value: 'cheat' },
					{ name: 'Done', value: 'done' },
					{ name: 'Expired', value: 'expired' },
					{ name: 'Open (In Flight)', value: 'open' },
					{ name: 'Rejected', value: 'rejected' },
				],
				routing: { send: { type: 'query', property: 'status' } },
			},
		],
	},

	// ── Get Ledger ──
	{
		displayName: 'Filters',
		name: 'ledgerFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: show('job', ['getLedger']),
		options: [
			{
				displayName: 'Client',
				name: 'client',
				type: 'string',
				default: '',
				placeholder: '0x…',
				routing: { send: { type: 'query', property: 'client' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'query', property: 'limit' } },
			},
			{
				displayName: 'Participant',
				name: 'participant',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'Client, provider or evaluator',
				routing: { send: { type: 'query', property: 'participant' } },
			},
			{
				displayName: 'Provider',
				name: 'provider',
				type: 'string',
				default: '',
				placeholder: '0x…',
				routing: { send: { type: 'query', property: 'provider' } },
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'active',
				description:
					'A ledger state such as <code>completed</code>, <code>expired</code>, <code>budget_set</code>, or the alias <code>active</code> for anything not yet terminal. Rows report their real state, never the word "active".',
				routing: { send: { type: 'query', property: 'state' } },
			},
			{
				displayName: 'Verify Mode',
				name: 'verify',
				type: 'string',
				default: '',
				placeholder: 'self',
				routing: { send: { type: 'query', property: 'verify' } },
			},
		],
	},

	// ── Create Offer ──
	{
		displayName: 'Chain',
		name: 'chainId',
		type: 'options',
		options: ASSURANCE_CHAINS,
		default: 8453,
		required: true,
		description: 'The assurance contracts are deployed on these chains',
		displayOptions: show('job', ['createOffer']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		...address('Seller', 'seller', 'job', ['createOffer'], 'The agent being hired.'),
		routing: { send: { type: 'body', property: 'seller' } },
	},
	{
		displayName: 'Price (Smallest Unit)',
		name: 'price',
		type: 'string',
		default: '',
		required: true,
		placeholder: '100000000',
		description: 'An integer in the token\'s smallest unit. 100 USDC is <code>100000000</code>.',
		displayOptions: show('job', ['createOffer']),
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Options',
		name: 'offerOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('job', ['createOffer']),
		options: [
			{
				displayName: 'Coverage Pool',
				name: 'pool',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description:
					'The seller\'s coverage pool. With no pool named, no premium is charged: a premium nobody earned would be a rent.',
				routing: { send: { type: 'body', property: 'pool' } },
			},
			{
				displayName: 'Deadline (Hours)',
				name: 'deadline_hours',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 720 },
				default: 24,
				routing: { send: { type: 'body', property: 'deadline_hours' } },
			},
			{
				displayName: 'Handshake ID',
				name: 'handshake_id',
				type: 'string',
				default: '',
				placeholder: 'hs_…',
				description: 'Attach the new job to a handshake so it can be followed there',
				routing: { send: { type: 'body', property: 'handshake_id' } },
			},
			{
				displayName: 'Settlement Asset Address',
				name: 'settlementAsset',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'The ERC-20 the job settles in. Defaults to USDC on Base; required on any other chain.',
				routing: { send: { type: 'body', property: 'token' } },
			},
		],
	},
];
