import type { INodeProperties } from 'n8n-workflow';
import { ASSURANCE_CHAINS, show } from './shared';

/**
 * The judge: grade work with a calibrated model (TypeSafe/Jev, rented through the layer on your quota or your own
 * key), then leave the trail on chain — a stamp on the immutable grade registry and, where the seller is a registered
 * agent, ERC-8004 reputation feedback. Every write here is an UNSIGNED call; send it with the Taifoon Devnet Signer
 * node (free gas, devnet) or your own wallet on Base/Arc.
 *
 * Stages (GET /v1/hiring/stages): verdict (grade, postVerdict) → record (stamp, giveFeedback, ready, trace).
 */
export const judgeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['judge'] } },
		options: [
			{
				name: 'Compose Verdict',
				value: 'compose',
				action: 'Compose the verdict on a hire',
				description: 'RUBRIC_v1 on a handshake or a job: code proves the facts, Jev answers four atomic questions on the evidence plus those facts, code composes the verdict. One call, or two steps (Prepare → your TypeSafe node → Answers) on your own TypeSafe credential. Answers with the receipt and the recorded decision (ID, digest, anchor). Stage: verdict.',
				routing: { request: { method: 'POST', url: '/judge/compose' } },
			},
			{
				name: 'Get Ready Jobs',
				value: 'getReady',
				action: 'List jobs ready for a grade',
				description: 'Settled or rejected ERC-8183 jobs with their seller record folded in and calibrated:true|false. Stage: record.',
				// the query rides as `qs`, never inside an expression URL: n8n encodes the `?` of an expression URL, the gateway then
				// sees the path "/judge/ready?chain=…" and answers 404 "no operation" (the 2026-09-23 defect)
				routing: { request: { method: 'GET', url: '/judge/ready', qs: { chain: '={{$parameter["readyChain"]}}', limit: '={{$parameter["readyLimit"]}}' } } },
			},
			{
				name: 'Get Reviewable Jobs',
				value: 'getReviewable',
				action: 'List paid deliveries worth reviewing',
				description: 'Paid, non-self-dealing ERC-8183 jobs (the Virtuals ACP contract on Base, paid in USDC) with createdAt — where your own chain read starts — and the GRID a review earns. The work behind the reviewers’ 20%. Stage: record.',
				routing: { request: { method: 'GET', url: '/grid/review' } },
			},
			{
				name: 'Get Stages',
				value: 'getStages',
				action: 'Get the stages of a hire',
				description: 'The stages of a hire as the whitepaper defines them and this layer implements them, with the operations that perform each',
				routing: { request: { method: 'GET', url: '/hiring/stages' } },
			},
			{
				name: 'Get Trace',
				value: 'getTrace',
				action: 'Read a job s on chain trail',
				description: 'Every ERC-8183 event of a job read live with explorer links, the deterministic ending, the recorded grade, the registry stamps and the devnet feedback. Stage: settlement → record.',
				routing: { request: { method: 'GET', url: '=/judge/trace/{{$parameter["traceChain"]}}/{{$parameter["traceJobId"]}}' } },
			},
			{
				name: 'Give Feedback (Unsigned)',
				value: 'giveFeedback',
				action: 'Build the unsigned ERC-8004 feedback call',
				description: 'The grade as reputation feedback about an agent: tag1 jev-grade, tag2 the verdict, value the confidence in hundredths, feedbackHash the digest. Stage: record.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
			{
				name: 'Grade',
				value: 'grade',
				action: 'Grade items with one calibrated call',
				description: 'Up to 4 items in ONE call on the free quota (12 with your own key): each item comes back with its full distribution, confidence, ending, digest and subject. Stage: verdict.',
				routing: { request: { method: 'POST', url: '/judge/grade' } },
			},
			{
				name: 'Judge One',
				value: 'judgeRef',
				action: 'Ask the judge one closed question',
				description: 'One item, one question, a closed list of answers: value · probabilities · confidence. Stage: verdict.',
				routing: { request: { method: 'POST', url: '/judge/ref' } },
			},
			{
				name: 'Post Verdict (Unsigned)',
				value: 'postVerdict',
				action: 'Build the unsigned post verdict call',
				description: 'The grade digest goes through the JudgeAdapter, which drives the hook’s ending (devnet). Stage: verdict → settlement.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
			{
				name: 'Record Answers',
				value: 'recordAnswers',
				action: 'Record jev answers on chain',
				description: 'Record what your TypeSafe node answered (every question, value, the whole distribution, model, latency) as a jev.answer.v1 record: stored by the layer and anchored as digests on the devnet JevAnswerLog. For answers that do not go through Compose Verdict (a batch, a demo, a gate); Compose → Answers records its answers by itself. Stage: record.',
				routing: { request: { method: 'POST', url: '/judge/answers/record' } },
			},
			{
				name: 'Submit Review',
				value: 'submitReview',
				action: 'Report a delivery you read from chain',
				description: 'Every event you read through YOUR RPC (tx, log index, block, block hash). The gateway reads the job itself and credits only an exact match — at most 3 reviewers a job, each once. Optional: attach a Jev grade. GRID points on the ledger. Stage: record.',
				routing: { request: { method: 'POST', url: '/grid/review' } },
			},
		],
		default: 'grade',
	},
	// ── compose ──
	{
		displayName: 'Subject',
		name: 'composeSubject',
		type: 'options',
		default: 'handshake',
		options: [
			{ name: 'Handshake', value: 'handshake', description: 'A brokered hire with its delivery on record' },
			{ name: 'Job', value: 'job', description: 'An ERC-8183 job read from the chain' },
		],
		displayOptions: show('judge', ['compose']),
	},
	{
		displayName: 'Handshake ID',
		name: 'composeHandshakeId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'hs_…',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeSubject: ['handshake'] } },
		routing: { send: { type: 'body', property: 'handshake_id' } },
	},
	{
		displayName: 'Job ID',
		name: 'composeJobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '80926 or 0x…',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeSubject: ['job'] } },
		routing: { send: { type: 'body', property: 'jobId' } },
	},
	{
		displayName: 'Chain',
		name: 'composeChainId',
		type: 'options',
		default: 8453,
		options: ASSURANCE_CHAINS,
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeSubject: ['job'] } },
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		displayName: 'Price (USDC)',
		name: 'composePriceUsdc',
		type: 'number',
		default: 0,
		description: 'The price the verdict is composed against (the auto-complete cap is 50 USDC); 0 = not given',
		displayOptions: show('judge', ['compose']),
		routing: { send: { type: 'body', property: 'price_usdc', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Mode',
		name: 'composeMode',
		type: 'options',
		default: 'single',
		options: [
			{ name: 'Answers (From Your TypeSafe Node)', value: 'answers', description: 'Step 2: send the answers your own TypeSafe node gave to the prepared questions; the layer checks the digest and every answer, composes and records the decision and the answers (caller-credential; see decision.answers_digest); Record On puts both on chain' },
			{ name: 'One Call (Layer Asks Jev)', value: 'single', description: 'The layer asks Jev itself: your 3 free grades per caller, then bought grades, or the key below' },
			{ name: 'Prepare (Your Own TypeSafe Credential)', value: 'prepare', description: 'Step 1: the facts (a hard fail is final here), the exact text Jev must read (the evidence plus the facts code established), the four questions every path asks, in the TypeSafe node schema, and a prepare digest. No judge call.' },
		],
		description: 'Two-step keeps the judge on your own TypeSafe credential: Prepare → TypeSafe node (connection Direct) → Answers',
		displayOptions: show('judge', ['compose']),
		routing: { send: { type: 'body', property: 'mode', value: '={{ $value === "single" ? undefined : $value }}' } },
	},
	{
		displayName: 'Answers (JSON)',
		name: 'composeAnswers',
		type: 'json',
		default: '={{ JSON.stringify($json.answers) }}',
		required: true,
		description: 'The TypeSafe node\'s <code>answers</code> (ID → value, confidence, probabilities) for the four prepared questions — the whole distribution, not a Pass/Fail',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'answers', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Model',
		name: 'composeModel',
		type: 'string',
		default: '={{ $json.model }}',
		required: true,
		description: 'The model the TypeSafe node reported',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'model' } },
	},
	{
		displayName: 'Prepare Digest',
		name: 'composePrepareDigest',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'The prepare_digest step 1 returned; the layer recomputes it and refuses a mismatch (the evidence changed)',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'prepare_digest' } },
	},
	{
		displayName: 'Answered By',
		name: 'composeAnsweredBy',
		type: 'options',
		default: 'n8n-typesafe',
		options: [{ name: 'Taifoon TypeSafe Node', description: 'The @taifoon/n8n-nodes-typesafe Ask operation, connection Direct', value: 'n8n-typesafe' }],
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'answered_by' } },
	},
	{
		displayName: 'Execution ID',
		name: 'composeExecutionId',
		type: 'string',
		default: '={{ $execution.id }}',
		description: 'Recorded with the decision so the answers can be traced to this run',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'execution_id', value: '={{ $value ? String($value) : undefined }}' } },
	},
	{
		displayName: 'Latency (Ms)',
		name: 'composeLatencyMs',
		type: 'number',
		default: 0,
		description: 'The TypeSafe node\'s latency_ms (map it from the node), recorded with the decision; 0 = not given',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers'] } },
		routing: { send: { type: 'body', property: 'latency_ms', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Record On',
		name: 'composeRecord',
		type: 'options',
		default: 'none',
		options: [
			{ name: 'Base', value: 'base', description: 'The layer\'s recorder writes the decision and the answers on Base (JevDecisionLog, JevAnswerLog), within its daily budget; over it the decision says why (decision.recording.held)' },
			{ name: 'Base and Devnet', value: 'both' },
			{ name: 'Devnet 36927', value: 'devnet', description: 'The decision and the answers are anchored on the Taifoon devnet logs' },
			{ name: 'None', value: 'none', description: 'Nothing is written on chain: the receipt, the decision and both digests are returned and stored' },
		],
		description: 'Opt-in: whether the composed decision and its answers are also written on chain. Default none.',
		displayOptions: { show: { resource: ['judge'], operation: ['compose'], composeMode: ['answers', 'single'] } },
		routing: { send: { type: 'body', property: 'record', value: '={{ $value === "none" ? undefined : $value }}' } },
	},
	// ── record answers (_JEV_RECORD_v1_) ──
	{
		displayName: 'Use Case',
		name: 'recordUseCase',
		type: 'options',
		default: 'n8n.batch',
		options: [
			{ name: 'Batch (N8n)', value: 'n8n.batch', description: 'A batch of REF answers from the TypeSafe node' },
			{ name: 'Compose Answers', value: 'compose.answers', description: 'RUBRIC_v1 answers you did not send through Compose → Answers' },
			{ name: 'Grade', value: 'grade', description: 'REF answers about delivered work' },
			{ name: 'Judge One (REF)', value: 'ref', description: 'One REF question' },
		],
		description: 'What Jev was asked — the name goes on chain as keccak256(name)',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'use_case' } },
	},
	{
		displayName: 'Subject',
		name: 'recordSubject',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'hs_… | 81067 | 0x…(32 bytes)',
		description: 'What the answers are about: a handshake ID, a job ID, a batch ID, or a 32-byte hex (anything else is keccak\'d)',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'subject' } },
	},
	{
		displayName: 'Text Jev Read',
		name: 'recordInput',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '={{ typeof $json.state === "string" ? $json.state : JSON.stringify($json.state ?? "") }}',
		description: 'Exactly the state you sent the TypeSafe node. Only its sha256 is kept (input_digest); the text is not stored and never goes on chain.',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'input', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Questions (JSON)',
		name: 'recordQuestions',
		type: 'json',
		default: '[]',
		description: 'The questions you asked: [{ ID, kind (choice|noul|score), text, options }] — the same list the TypeSafe node received',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'questions', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'TypeSafe Reply (JSON)',
		name: 'recordReply',
		type: 'json',
		default: '={{ JSON.stringify({ answers: $json.answers }) }}',
		required: true,
		description: 'The TypeSafe node output with its <code>answers</code> (either the array form or ID → { value, probabilities, confidence } / { p }) — the whole distribution is recorded',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'jev', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Model',
		name: 'recordModel',
		type: 'string',
		default: '={{ $json.model ?? "jev" }}',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'model', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Upstream Model',
		name: 'recordUpstreamModel',
		type: 'string',
		default: '={{ $json.upstreamModel ?? "" }}',
		description: 'The TypeSafe node\'s upstreamModel (e.g. jev-1.13.0)',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'upstream_model', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Latency (Ms)',
		name: 'recordLatencyMs',
		type: 'number',
		default: 0,
		description: 'The TypeSafe node\'s latency_ms; 0 = not given',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'latency_ms', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Decision Digest',
		name: 'recordDecisionDigest',
		type: 'string',
		default: '',
		placeholder: '0x…',
		description: 'When a decision was composed from these answers, its digest (bound on chain beside the answers); empty = none',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'decision_digest', value: '={{ $value || undefined }}' } },
	},
	{
		// constants ride on hidden fields (an option-level routing.request.body is dropped by n8n — the Stamp Grade lesson)
		displayName: 'Credential Path',
		name: 'recordCredentialPath',
		type: 'hidden',
		default: 'caller-credential',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'credential_path' } },
	},
	{
		displayName: 'Caller',
		name: 'recordCaller',
		type: 'hidden',
		default: 'n8n',
		displayOptions: show('judge', ['recordAnswers']),
		routing: { send: { type: 'body', property: 'caller' } },
	},
	// ── grade ──
	{
		displayName: 'Items (JSON)',
		name: 'items',
		type: 'json',
		default: '[{"id":"81067","state":"…the pre-verdict trail or the deliverable…"}]',
		required: true,
		description: 'An array of { ID, state }: state is the item to judge, as text or JSON (the ready-jobs rows carry one as <code>state</code>)',
		displayOptions: show('judge', ['grade']),
		routing: { send: { type: 'body', property: 'items', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Question',
		name: 'question',
		type: 'string',
		default: 'Was the work delivered as specified?',
		description: 'One closed question; the answers are the four endings unless you set Options',
		displayOptions: show('judge', ['grade', 'judgeRef']),
		routing: { send: { type: 'body', property: 'question' } },
	},
	{
		displayName: 'Options (Comma-Separated)',
		name: 'options',
		type: 'string',
		default: '',
		placeholder: 'delivered_as_specified, delivered_with_defects, not_delivered, cannot_determine',
		description: 'The closed list of answers; empty = the four endings',
		displayOptions: show('judge', ['grade', 'judgeRef']),
		routing: { send: { type: 'body', property: 'options', value: '={{ $value ? $value.split(",").map((s) => s.trim()).filter((s) => s) : undefined }}' } },
	},
	{
		displayName: 'State (Item to Judge)',
		name: 'state',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		description: 'The item, as text or JSON: the task, the deliverable, whatever the question is about',
		displayOptions: show('judge', ['judgeRef']),
		routing: { send: { type: 'body', property: 'state' } },
	},
	{
		displayName: 'Your TypeSafe Key',
		name: 'key',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		description: 'Optional. Your own TypeSafe key: the call is billed to it and nobody else is in the path. Empty = your 3 free grades per caller (account, API key or address), then bought grades.',
		// the two-step compose never sends a key: the answers come from your own TypeSafe node
		displayOptions: { ...show('judge', ['grade', 'judgeRef', 'compose']), hide: { composeMode: ['prepare', 'answers'] } },
		routing: { send: { type: 'body', property: 'key', value: '={{ $value || undefined }}' } },
	},
	// ── review ──
	{
		displayName: 'Owner Wallet',
		name: 'reviewOwner',
		type: 'string',
		default: '',
		placeholder: '0x…',
		description: 'The wallet your Grid node joined with (TAIFOON_OWNER). Points go to the wallet BOUND to your relayer key: bind once by sending this with Owner Signature; after that it may be left empty, and a different wallet is refused.',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'owner', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Owner Signature (Binding, Once)',
		name: 'reviewOwnerSignature',
		type: 'string',
		default: '',
		placeholder: '0x… (65 bytes)',
		description: 'Only for the first review from this key (or to re-bind): the owner wallet\'s personal_sign of "Taifoon Grid reviewer\\nowner: OWNER (lower-case)\\nkey: KEY_PREFIX". A 403 without it returns the exact message. It binds this wallet to this key only, so it is useless to anyone without the key.',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'owner_signature', value: '={{ $value || undefined }}' } },
	},
	{
		displayName: 'Chain',
		name: 'reviewChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }],
		default: 8453,
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		displayName: 'Job ID',
		name: 'reviewJobId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'jobId' } },
	},
	{
		displayName: 'Verdict',
		name: 'reviewVerdict',
		type: 'options',
		options: [
			{ name: 'Agree — I Read the Events the Feed Lists', value: 'agree' },
			{ name: 'Disagree — the Chain Differs From the Feed', value: 'disagree' },
		],
		default: 'agree',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'verdict' } },
	},
	{
		displayName: 'Evidence (JSON)',
		name: 'reviewEvidence',
		type: 'json',
		default: '[]',
		required: true,
		description: 'Array of { event, tx, log_index, block, block_hash } — every event of the job, read from chain through your own RPC',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'evidence', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Jev Grade (JSON, Optional)',
		name: 'reviewJev',
		type: 'json',
		default: '',
		description: 'Optional: the calibrated judge’s grade of this delivery, e.g. the item from Judge → Grade ({ value, confidence }). Recorded with the review; the credit depends on the chain match only.',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'jev', value: '={{ $value ? (typeof $value === "string" ? JSON.parse($value) : $value) : undefined }}' } },
	},
	// ── ready ──
	{
		displayName: 'Chain',
		name: 'readyChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }, { name: 'Arc (5042)', value: 5042 }, { name: 'Robinhood (4663)', value: 4663 }],
		default: 8453,
		displayOptions: show('judge', ['getReady']),
	},
	{
		displayName: 'Limit',
		name: 'readyLimit',
		type: 'number',
		default: 40,
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: show('judge', ['getReady']),
	},
	// ── trace / verdict ──
	{
		displayName: 'Chain',
		name: 'chainId',
		type: 'options',
		options: ASSURANCE_CHAINS,
		default: 8453,
		required: true,
		displayOptions: show('judge', ['postVerdict', 'giveFeedback']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		displayName: 'Chain',
		name: 'traceChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }, { name: 'Arc (5042)', value: 5042 }, { name: 'Taifoon Devnet (36927)', value: 36927 }],
		default: 8453,
		required: true,
		displayOptions: show('judge', ['getTrace']),
	},
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '81067 (ERC-8183 ID) or 0x… (bytes32 on the assurance hook)',
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.jobId' } },
	},
	{
		displayName: 'Job ID',
		name: 'traceJobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '81067 (ERC-8183 ID)',
		displayOptions: show('judge', ['getTrace']),
	},
	{ displayName: 'Kind', name: 'verdictKind', type: 'hidden', default: 'post-verdict', displayOptions: show('judge', ['postVerdict']), routing: { send: { type: 'body', property: 'action.kind' } } },
	{
		displayName: 'Verdict',
		name: 'verdict',
		type: 'options',
		options: [{ name: '1 · Conformant → the Hook Completes', value: 1 }, { name: '2 · Nonconformant → Rejects', value: 2 }, { name: '3 · Malformed → Rejects, Never a Cheat', value: 3 }],
		default: 2,
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.verdict' } },
	},
	{
		displayName: 'Mode',
		name: 'verdictMode',
		type: 'options',
		options: [{ name: '1 · Deterministic (a Digest Anyone Recomputes)', value: 1 }, { name: '2 · Calibrated (an Attestation From the Judge, Never a Proof)', value: 2 }],
		default: 2,
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.mode' } },
	},
	{
		displayName: 'Digest (Bytes32)',
		name: 'digest',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'The grade digest the Grade operation returned (sha256 over the canonical grade)',
		displayOptions: show('judge', ['postVerdict', 'giveFeedback']),
		routing: { send: { type: 'body', property: 'action.digest' } },
	},
	// ── feedback ──
	{ displayName: 'Kind', name: 'feedbackKind', type: 'hidden', default: 'give-feedback', displayOptions: show('judge', ['giveFeedback']), routing: { send: { type: 'body', property: 'action.kind' } } },
	{
		displayName: 'Agent ID',
		name: 'agentId',
		type: 'string',
		default: '',
		required: true,
		description: 'The agent on this chain’s ERC-8004 identity registry (on the devnet: a mirror’s ID — see /v1/onboarding/batch graded[].feedback_8004.devnet)',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.agentId' } },
	},
	{
		displayName: 'Verdict (Tag2)',
		name: 'feedbackVerdict',
		type: 'options',
		options: [{ name: 'Delivered As Specified', value: 'delivered_as_specified' }, { name: 'Delivered With Defects', value: 'delivered_with_defects' }, { name: 'Not Delivered', value: 'not_delivered' }, { name: 'Cannot Determine', value: 'cannot_determine' }],
		default: 'cannot_determine',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.verdict' } },
	},
	{
		displayName: 'Confidence (0–1)',
		name: 'confidence',
		type: 'number',
		default: 0.9,
		typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
		description: 'Becomes value in hundredths (2 decimals) on the registry',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.confidence' } },
	},
	{
		displayName: 'Endpoint',
		name: 'endpoint',
		type: 'string',
		default: '',
		description: 'The agent’s endpoint, optional',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.endpoint' } },
	},
	{
		displayName: 'Feedback URI',
		name: 'feedbackURI',
		type: 'string',
		default: 'https://www.taifoon.io/v1/onboarding/batch',
		description: 'Where the long form of the grade lives',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.feedbackURI' } },
	},
];
