import type { INodeProperties } from 'n8n-workflow';
import { ASSURANCE_CHAINS, show } from './shared';

/**
 * The judge: grade work with a calibrated model (TypeSafe/Jev, rented through the layer on your quota or your own
 * key), then leave the trail on chain — a stamp on the immutable grade registry and, where the seller is a registered
 * agent, ERC-8004 reputation feedback. Every write here is an UNSIGNED call; send it with the Taifoon Devnet Signer
 * node (free gas, devnet) or your own wallet on Base/Arc.
 *
 * Stages (GET /v1/hiring/stages): verdict (grade, postVerdict) → record (stamp, giveFeedback, ready, trace).
 */
export const judgeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['judge'] } },
		options: [
			{
				name: 'Get Ready Jobs',
				value: 'getReady',
				action: 'List jobs ready for a grade',
				description: 'Settled or rejected ERC-8183 jobs with their seller record folded in and calibrated:true|false. Stage: record.',
				// the query rides as `qs`, never inside an expression URL: n8n encodes the `?` of an expression URL, the gateway then
				// sees the path "/judge/ready?chain=…" and answers 404 "no operation" (the 2026-09-23 defect)
				routing: { request: { method: 'GET', url: '/judge/ready', qs: { chain: '={{$parameter["readyChain"]}}', limit: '={{$parameter["readyLimit"]}}' } } },
			},
			{
				name: 'Get Reviewable Jobs',
				value: 'getReviewable',
				action: 'List paid deliveries worth reviewing',
				description: 'Paid, non-self-dealing ERC-8183 jobs (the Virtuals ACP contract on Base, paid in USDC) with createdAt — where your own chain read starts — and the GRID a review earns. The work behind the reviewers’ 20%. Stage: record.',
				routing: { request: { method: 'GET', url: '/grid/review' } },
			},
			{
				name: 'Get Stages',
				value: 'getStages',
				action: 'Get the stages of a hire',
				description: 'The stages of a hire as the whitepaper defines them and this layer implements them, with the operations that perform each',
				routing: { request: { method: 'GET', url: '/hiring/stages' } },
			},
			{
				name: 'Get Trace',
				value: 'getTrace',
				action: 'Read a job s on chain trail',
				description: 'Every ERC-8183 event of a job read live with explorer links, the deterministic ending, the recorded grade, the registry stamps and the devnet feedback. Stage: settlement → record.',
				routing: { request: { method: 'GET', url: '=/judge/trace/{{$parameter["traceChain"]}}/{{$parameter["traceJobId"]}}' } },
			},
			{
				name: 'Give Feedback (Unsigned)',
				value: 'giveFeedback',
				action: 'Build the unsigned ERC-8004 feedback call',
				description: 'The grade as reputation feedback about an agent: tag1 jev-grade, tag2 the verdict, value the confidence in hundredths, feedbackHash the digest. Stage: record.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
			{
				name: 'Grade',
				value: 'grade',
				action: 'Grade items with one calibrated call',
				description: 'Up to 4 items in ONE call on the free quota (12 with your own key): each item comes back with its full distribution, confidence, ending, digest and subject. Stage: verdict.',
				routing: { request: { method: 'POST', url: '/judge/grade' } },
			},
			{
				name: 'Judge One',
				value: 'judgeRef',
				action: 'Ask the judge one closed question',
				description: 'One item, one question, a closed list of answers: value · probabilities · confidence. Stage: verdict.',
				routing: { request: { method: 'POST', url: '/judge/ref' } },
			},
			{
				name: 'Post Verdict (Unsigned)',
				value: 'postVerdict',
				action: 'Build the unsigned post verdict call',
				description: 'The grade digest goes through the JudgeAdapter, which drives the hook’s ending (devnet). Stage: verdict → settlement.',
				routing: { request: { method: 'POST', url: '/assurance/call' } },
			},
			{
				name: 'Submit Review',
				value: 'submitReview',
				action: 'Report a delivery you read from chain',
				description: 'Every event you read through YOUR RPC (tx, log index, block, block hash). The gateway reads the job itself and credits only an exact match — at most 3 reviewers a job, each once. Optional: attach a Jev grade. GRID points on the ledger. Stage: record.',
				routing: { request: { method: 'POST', url: '/grid/review' } },
			},
		],
		default: 'grade',
	},
	// ── grade ──
	{
		displayName: 'Items (JSON)',
		name: 'items',
		type: 'json',
		default: '[{"id":"81067","state":"…the pre-verdict trail or the deliverable…"}]',
		required: true,
		description: 'An array of { ID, state }: state is the item to judge, as text or JSON (the ready-jobs rows carry one as <code>state</code>)',
		displayOptions: show('judge', ['grade']),
		routing: { send: { type: 'body', property: 'items', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Question',
		name: 'question',
		type: 'string',
		default: 'Was the work delivered as specified?',
		description: 'One closed question; the answers are the four endings unless you set Options',
		displayOptions: show('judge', ['grade', 'judgeRef']),
		routing: { send: { type: 'body', property: 'question' } },
	},
	{
		displayName: 'Options (Comma-Separated)',
		name: 'options',
		type: 'string',
		default: '',
		placeholder: 'delivered_as_specified, delivered_with_defects, not_delivered, cannot_determine',
		description: 'The closed list of answers; empty = the four endings',
		displayOptions: show('judge', ['grade', 'judgeRef']),
		routing: { send: { type: 'body', property: 'options', value: '={{ $value ? $value.split(",").map((s) => s.trim()).filter((s) => s) : undefined }}' } },
	},
	{
		displayName: 'State (Item to Judge)',
		name: 'state',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		description: 'The item, as text or JSON: the task, the deliverable, whatever the question is about',
		displayOptions: show('judge', ['judgeRef']),
		routing: { send: { type: 'body', property: 'state' } },
	},
	{
		displayName: 'Your TypeSafe Key',
		name: 'key',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		description: 'Optional. Your own TypeSafe key: the call is billed to it and nobody else is in the path. Empty = the free calls on your API key’s quota.',
		displayOptions: show('judge', ['grade', 'judgeRef']),
		routing: { send: { type: 'body', property: 'key', value: '={{ $value || undefined }}' } },
	},
	// ── review ──
	{
		displayName: 'Owner Wallet',
		name: 'reviewOwner',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'The wallet your Grid node joined with (TAIFOON_OWNER) — reviews are work a node does',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'owner' } },
	},
	{
		displayName: 'Chain',
		name: 'reviewChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }],
		default: 8453,
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		displayName: 'Job ID',
		name: 'reviewJobId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'jobId' } },
	},
	{
		displayName: 'Verdict',
		name: 'reviewVerdict',
		type: 'options',
		options: [
			{ name: 'Agree — I Read the Events the Feed Lists', value: 'agree' },
			{ name: 'Disagree — the Chain Differs From the Feed', value: 'disagree' },
		],
		default: 'agree',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'verdict' } },
	},
	{
		displayName: 'Evidence (JSON)',
		name: 'reviewEvidence',
		type: 'json',
		default: '[]',
		required: true,
		description: 'Array of { event, tx, log_index, block, block_hash } — every event of the job, read from chain through your own RPC',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'evidence', value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}' } },
	},
	{
		displayName: 'Jev Grade (JSON, Optional)',
		name: 'reviewJev',
		type: 'json',
		default: '',
		description: 'Optional: the calibrated judge’s grade of this delivery, e.g. the item from Judge → Grade ({ value, confidence }). Recorded with the review; the credit depends on the chain match only.',
		displayOptions: show('judge', ['submitReview']),
		routing: { send: { type: 'body', property: 'jev', value: '={{ $value ? (typeof $value === "string" ? JSON.parse($value) : $value) : undefined }}' } },
	},
	// ── ready ──
	{
		displayName: 'Chain',
		name: 'readyChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }, { name: 'Arc (5042)', value: 5042 }, { name: 'Robinhood (4663)', value: 4663 }],
		default: 8453,
		displayOptions: show('judge', ['getReady']),
	},
	{
		displayName: 'Limit',
		name: 'readyLimit',
		type: 'number',
		default: 40,
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: show('judge', ['getReady']),
	},
	// ── trace / verdict ──
	{
		displayName: 'Chain',
		name: 'chainId',
		type: 'options',
		options: ASSURANCE_CHAINS,
		default: 8453,
		required: true,
		displayOptions: show('judge', ['postVerdict', 'giveFeedback']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		displayName: 'Chain',
		name: 'traceChain',
		type: 'options',
		options: [{ name: 'Base (8453)', value: 8453 }, { name: 'Arc (5042)', value: 5042 }, { name: 'Taifoon Devnet (36927)', value: 36927 }],
		default: 8453,
		required: true,
		displayOptions: show('judge', ['getTrace']),
	},
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '81067 (ERC-8183 ID) or 0x… (bytes32 on the assurance hook)',
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.jobId' } },
	},
	{
		displayName: 'Job ID',
		name: 'traceJobId',
		type: 'string',
		default: '',
		required: true,
		placeholder: '81067 (ERC-8183 ID)',
		displayOptions: show('judge', ['getTrace']),
	},
	{ displayName: 'Kind', name: 'verdictKind', type: 'hidden', default: 'post-verdict', displayOptions: show('judge', ['postVerdict']), routing: { send: { type: 'body', property: 'action.kind' } } },
	{
		displayName: 'Verdict',
		name: 'verdict',
		type: 'options',
		options: [{ name: '1 · Conformant → the Hook Completes', value: 1 }, { name: '2 · Nonconformant → Rejects', value: 2 }, { name: '3 · Malformed → Rejects, Never a Cheat', value: 3 }],
		default: 2,
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.verdict' } },
	},
	{
		displayName: 'Mode',
		name: 'verdictMode',
		type: 'options',
		options: [{ name: '1 · Deterministic (a Digest Anyone Recomputes)', value: 1 }, { name: '2 · Calibrated (an Attestation From the Judge, Never a Proof)', value: 2 }],
		default: 2,
		displayOptions: show('judge', ['postVerdict']),
		routing: { send: { type: 'body', property: 'action.mode' } },
	},
	{
		displayName: 'Digest (Bytes32)',
		name: 'digest',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x…',
		description: 'The grade digest the Grade operation returned (sha256 over the canonical grade)',
		displayOptions: show('judge', ['postVerdict', 'giveFeedback']),
		routing: { send: { type: 'body', property: 'action.digest' } },
	},
	// ── feedback ──
	{ displayName: 'Kind', name: 'feedbackKind', type: 'hidden', default: 'give-feedback', displayOptions: show('judge', ['giveFeedback']), routing: { send: { type: 'body', property: 'action.kind' } } },
	{
		displayName: 'Agent ID',
		name: 'agentId',
		type: 'string',
		default: '',
		required: true,
		description: 'The agent on this chain’s ERC-8004 identity registry (on the devnet: a mirror’s ID — see /v1/onboarding/batch graded[].feedback_8004.devnet)',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.agentId' } },
	},
	{
		displayName: 'Verdict (Tag2)',
		name: 'feedbackVerdict',
		type: 'options',
		options: [{ name: 'Delivered As Specified', value: 'delivered_as_specified' }, { name: 'Delivered With Defects', value: 'delivered_with_defects' }, { name: 'Not Delivered', value: 'not_delivered' }, { name: 'Cannot Determine', value: 'cannot_determine' }],
		default: 'cannot_determine',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.verdict' } },
	},
	{
		displayName: 'Confidence (0–1)',
		name: 'confidence',
		type: 'number',
		default: 0.9,
		typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
		description: 'Becomes value in hundredths (2 decimals) on the registry',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.confidence' } },
	},
	{
		displayName: 'Endpoint',
		name: 'endpoint',
		type: 'string',
		default: '',
		description: 'The agent’s endpoint, optional',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.endpoint' } },
	},
	{
		displayName: 'Feedback URI',
		name: 'feedbackURI',
		type: 'string',
		default: 'https://www.taifoon.io/v1/onboarding/batch',
		description: 'Where the long form of the grade lives',
		displayOptions: show('judge', ['giveFeedback']),
		routing: { send: { type: 'body', property: 'action.feedbackURI' } },
	},
];
