import type { INodeProperties } from 'n8n-workflow';
import { show, address, ASSURANCE_CHAINS } from './shared';

/**
 * Settlement — the last step of a hire. One paid call (a judge call, a call to another agent, a grid
 * resource call) becomes one insured job on the assurance hook: the seller of record locks its deposit,
 * the buyer funds price + premium, the seller submits the evidence digest, the buyer completes, and the
 * x402 capture binds the payment to the job. `Settle` answers with the UNSIGNED calls in that order,
 * each labelled with who sends it; on the devnet (36927, free gas) the Taifoon Devnet Signer sends them.
 * Nothing here signs.
 */
export const settlementOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['settlement'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				action: 'Get one recorded settlement',
				description: 'One settlement as the runner recorded it: kind, chain, job ID, correlator, every transaction with its receipt and explorer link, the V5 receipt-proof link',
				routing: { request: { method: 'GET', url: '=/settle/{{$parameter.settlementId}}' } },
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get the settlements recorded on the layer',
				description: 'Settlements recorded on the coordination layer, newest first',
				routing: { request: { method: 'GET', url: '/settle' } },
			},
			{
				name: 'Settle',
				value: 'settle',
				action: 'Plan the settlement of one paid call',
				description: 'The unsigned settlement of one paid call on the assurance hook: job ID, x402 nonce and correlator, token, price / premium / deposit, and calls[] in order — each says who signs. Stage: settlement.',
				routing: { request: { method: 'POST', url: '/settle' } },
			},
		],
		default: 'settle',
	},
	{
		displayName: 'Settlement ID',
		name: 'settlementId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: show('settlement', ['get']),
	},
	{
		displayName: 'Kind',
		name: 'kind',
		type: 'options',
		default: 'agent',
		required: true,
		options: [
			{ name: 'Agent Call', value: 'agent', description: 'A call to another agent: the reply is the deliverable, its digest is the evidence' },
			{ name: 'Judge Call', value: 'jev', description: 'A judge call: the grade is the deliverable, its digest is the evidence' },
			{ name: 'Resource Call', value: 'resource', description: 'A grid resource call: the oracle’s record is the evidence' },
		],
		displayOptions: show('settlement', ['settle']),
		routing: { send: { type: 'body', property: 'kind' } },
	},
	{
		displayName: 'Chain',
		name: 'chainId',
		type: 'options',
		default: 36927,
		required: true,
		options: ASSURANCE_CHAINS,
		description: 'Where the settlement runs. The devnet has free gas and public dev accounts; Base and Arc need real signers.',
		displayOptions: show('settlement', ['settle']),
		routing: { send: { type: 'body', property: 'chainId' } },
	},
	{
		...address('Buyer', 'buyer', 'settlement', ['settle'], 'Who funds the job: price + premium into escrow.'),
		routing: { send: { type: 'body', property: 'buyer' } },
	},
	{
		...address(
			'Seller of Record',
			'seller',
			'settlement',
			['settle'],
			'Who locks the deposit and submits the evidence: an agent’s own wallet, a node owner, the judge account, or the reseller’s seller of record for an agent that has none.',
		),
		routing: { send: { type: 'body', property: 'seller' } },
	},
	{
		displayName: 'Price (Smallest Units)',
		name: 'price',
		type: 'string',
		default: '1000000',
		required: true,
		description: 'In the settlement token’s smallest unit (1000000 = 1.00 of a 6-decimal dollar). Premium defaults to 1% of it, deposit to 2 × price + 1.',
		displayOptions: show('settlement', ['settle']),
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Evidence Digest',
		name: 'evidence',
		type: 'string',
		default: '',
		required: true,
		placeholder: '0x… (32 bytes)',
		description: 'The 32-byte digest the seller submits: the reply digest of a delivery (Handshake → Get: reply_digest), the grade digest of a decision, or a probe record',
		displayOptions: show('settlement', ['settle']),
		routing: { send: { type: 'body', property: 'evidence' } },
	},
	{
		displayName: 'Reference ID',
		name: 'refId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'hs_… or a decision ID',
		description: 'What was called. Hashed into the job ID with the kind and the evidence, so the same call settles to the same job.',
		displayOptions: show('settlement', ['settle']),
		routing: { send: { type: 'body', property: 'ref.id' } },
	},
	{
		displayName: 'Options',
		name: 'settleOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: show('settlement', ['settle']),
		options: [
			{
				displayName: 'Deadline (Unix Seconds)',
				name: 'deadline',
				type: 'number',
				default: 0,
				description: 'Default: one hour from now',
				routing: { send: { type: 'body', property: 'deadline', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Deposit (Smallest Units)',
				name: 'deposit',
				type: 'string',
				default: '',
				description: 'Must exceed the price (D &gt; P). Default 2 × price + 1.',
				routing: { send: { type: 'body', property: 'deposit', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Endpoint',
				name: 'endpoint',
				type: 'string',
				default: '',
				description: 'The endpoint that was called, kept for the record',
				routing: { send: { type: 'body', property: 'ref.endpoint', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Hook Address',
				name: 'hook',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'Another deployment of the same hook; every call and approval targets it',
				routing: { send: { type: 'body', property: 'hook', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Note',
				name: 'note',
				type: 'string',
				default: '',
				description: 'Kept for the record — the judge decision ID, the agent that did the work, anything the settlement should remember',
				routing: { send: { type: 'body', property: 'ref.note', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Pool Address',
				name: 'pool',
				type: 'string',
				default: '',
				placeholder: '0x…',
				description: 'The coverage pool that stands behind the seller on this job',
				routing: { send: { type: 'body', property: 'pool', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Premium (Smallest Units)',
				name: 'premium',
				type: 'string',
				default: '',
				description: 'Default 1% of the price, at least 1 unit',
				routing: { send: { type: 'body', property: 'premium', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Tenant',
				name: 'tenant',
				type: 'string',
				default: '',
				placeholder: 'moonbeam',
				description: 'A named tenant’s own deployment: its hook for every call, its token when none is given',
				routing: { send: { type: 'body', property: 'tenant', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Token Address',
				name: 'tokenAddress',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				placeholder: '0x…',
				description: 'The job’s token. Default: the chain’s settlement dollar (dUSDC on the devnet, USDC on Base and Arc).',
				routing: { send: { type: 'body', property: 'token', value: '={{ $value || undefined }}' } },
			},
		],
	},
];
