#!/usr/bin/env node
// The n8n flow, from its one definition (flow.json), the example workflows beside it and their last tested runs (runs/).
//   node examples/flow.mjs --write    regenerate README.md (and the CLI's vendored copy, when the CLI is beside this package)
//   node examples/flow.mjs --check    exit 1 when README.md or the vendored copy is stale
// Pure helpers are exported for flow.test.mjs.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (f) => JSON.parse(readFileSync(join(HERE, f), 'utf8'));
// the CLI ships the flow and the last runs as one file, so `taifoon demo n8n` needs no network to know the steps
export const CLI_COPY = join(HERE, '..', '..', '..', 'packages', 'cli', 'src', 'n8n-flow.json');

export function load() {
  const flow = read('flow.json');
  // the test inputs stay with the private test harness; the public tree has the flow, the workflows and runs/ only
  const inputs = existsSync(join(HERE, 'test-inputs.json')) ? read('test-inputs.json') : {};
  const examples = Object.fromEntries(readdirSync(HERE).filter((f) => /^\d+[a-z]?-.*\.json$/.test(f)).sort((a, b) => a.localeCompare(b, 'en', { numeric: true })).map((f) => [f, read(f)]));
  const runs = Object.fromEntries(Object.keys(examples).filter((f) => existsSync(join(HERE, 'runs', f))).map((f) => [f, JSON.parse(readFileSync(join(HERE, 'runs', f), 'utf8'))]));
  return { flow, inputs, examples, runs };
}

/** Every phase with its role, flattened. Pure. */
export const phases = (flow) => flow.roles.flatMap((r) => r.phases.map((p) => ({ role: r.id, ...p, ops: p.ops ?? [p.op] })));

/** The links a run's output carries (explorer, transactions), for the README, the page and the demo. Pure. */
export function runLinks(out) {
  const links = [];
  const walk = (v, k) => {
    if (typeof v === 'string' && /^https:\/\/www\.taifoon\.io\/scan\//.test(v)) links.push({ label: k, url: v });
    else if (v && typeof v === 'object') for (const [kk, vv] of Object.entries(v)) walk(vv, kk);
  };
  walk(out ?? {}, 'output');
  return links;
}

/** The one-file copy the CLI vendors: the flow, and per example its name, ops and last run (no node outputs beyond the last). Pure. */
export function cliCopy({ flow, examples, runs }) {
  return {
    schema: 'taifoon.n8n-flow.cli.v1',
    flow,
    examples: Object.fromEntries(Object.entries(examples).map(([f, w]) => [f, {
      id: w.id, name: w.name, ops: w.meta.taifoon.ops, description: w.meta.taifoon.description,
      run: runs[f] ? { verdict: runs[f].verdict, execution_id: runs[f].execution_id, where: runs[f].where, ran_at: runs[f].ran_at, wall_ms: runs[f].wall_ms, n8n: runs[f].n8n, node: runs[f].node, output: runs[f].output } : null,
    }])),
  };
}

const RAW = 'https://raw.githubusercontent.com/taifoon-io/n8n-nodes-taifoon/main/examples';
const code = (s) => '`' + s + '`';
const secs = (ms) => (ms >= 60_000 ? `${Math.floor(ms / 60_000)} min ${Math.round((ms % 60_000) / 1000)} s` : `${Math.round(ms / 1000)} s`);

/** README.md, generated. Pure. */
export function readme({ flow, inputs, examples, runs }) {
  const L = [];
  L.push('# n8n-nodes-taifoon examples', '');
  L.push('<!-- generated by examples/flow.mjs from flow.json, the workflows and runs/; edit those, then: node examples/flow.mjs --write -->', '');
  L.push(`Small workflows for the Taifoon node, one per step of the flow. Each one imports into n8n as it is, carries its instructions in a sticky note, and holds a credential placeholder only (never a key). Each was run inside n8n ${Object.values(runs)[0]?.n8n ?? ''} before it was published: the last run is under every example.`, '');
  L.push('**Import:** n8n → Workflows → Import from File (or paste the JSON). Install the community node `n8n-nodes-taifoon` first. Where a node needs a key, attach a **Taifoon Relayer API** credential (example 1a gets you a free key).', '');
  L.push(`Money and chain writes stay on the ${flow.network.label}. Nothing here signs or sends a transaction.`, '');
  L.push('## The flow', '');
  for (const r of flow.roles) {
    L.push(`### ${r.title}`, '', r.line, '');
    L.push('| Phase | What happens | Node operation | Call | Example · node | Costs |', '|---|---|---|---|---|---|');
    for (const p of r.phases) L.push(`| ${p.title} | ${p.does} | ${(p.ops ?? [p.op]).map(code).join(', ')} | ${code(p.http)} | [${p.example.replace(/\.json$/, '')}](${p.example}) · ${p.nodes.join(', ')} | ${p.costs} |`);
    L.push('');
  }
  L.push('### GRID points and credits', '', `- **Earn:** ${flow.grid.earn} ([GRID](${flow.grid.join}))`, `- **Spend:** ${flow.grid.spend} (${code(flow.grid.spend_api)})`, `- **In this flow:** ${flow.grid.in_this_flow}`, '');
  L.push('## The examples', '');
  for (const [f, w] of Object.entries(examples)) {
    const t = w.meta.taifoon, spec = inputs[f] ?? {}, run = runs[f];
    L.push(`### ${w.name.replace(/^Taifoon example /, '')}`, '');
    L.push(`[${f}](${f}) · raw: ${RAW}/${f}`, '');
    L.push(t.description, '');
    L.push(`**Operations:** ${t.ops.map(code).join(', ')}`, '');
    L.push(`**Credential:** ${w.nodes.some((n) => n.credentials) ? 'Taifoon Relayer API on ' + w.nodes.filter((n) => n.credentials).map((n) => n.name).join(', ') : 'none (public reads)'}`, '');
    if (spec.expect) L.push(`**Expected output** (${code(spec.last)}): ${spec.expect.map(code).join(', ')}`, '');
    if (run) {
      const links = runLinks(run.output);
      L.push(`**Last run:** ${run.verdict.toUpperCase()} · ${run.where === 'hosted' ? 'n8n.taifoon.dev' : 'local n8n'} ${run.n8n}, node ${run.node} · execution ${run.execution_id ?? '(not saved)'} · ${run.ran_at.slice(0, 16).replace('T', ' ')} UTC · ${secs(run.wall_ms)}${links.length ? ' · ' + links.map((l) => `[${l.label}](${l.url})` ).join(' · ') : ''}`, '');
    }
  }
  L.push('## How they are tested', '');
  L.push('Before an example is published it is imported and executed headless inside n8n, and its last node is checked field by field: a null or empty field where data is expected fails it. The record of each last run is in [runs/](runs/). The runs are test-tagged: our own key, buyer labels that start with `ours:`, settlement on the devnet only, no paid call.', '');
  return L.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const d = load();
  const want = { [join(HERE, 'README.md')]: readme(d) };
  if (existsSync(dirname(CLI_COPY))) want[CLI_COPY] = JSON.stringify(cliCopy(d), null, 1) + '\n';
  const stale = Object.entries(want).filter(([p, s]) => !existsSync(p) || readFileSync(p, 'utf8') !== s).map(([p]) => p);
  if (process.argv.includes('--write')) { for (const [p, s] of Object.entries(want)) writeFileSync(p, s); console.log(`written: ${Object.keys(want).length} file(s)`); }
  else if (stale.length) { console.error(`stale: ${stale.join(', ')}\nrun: node n8n/coordination/examples/flow.mjs --write`); process.exit(1); }
  else console.log('ok');
}
